### ISSUE TITLE
Adopting features from RPG toolkit

### ISSUE THREAD

**Issue by erlend-sh** [fishfight/FishFight#121]
@olefasting is working on a genre-specific Macroquad-framework we could learn a lot from, and possibly even maintain stuff in common at the lightest abstraction layeres: https://github.com/olefasting/rust_rpg_toolkit

Features I’m interested in:

> - Easy definition and modification of game data and resources, without having to tuch source code
> - Mod support out-of-the-box with modules that can extend or replace a game's data and resources
> - RPG mechanics, like character stats, items and an inventory system
> Conversion from Tiled maps and instantiation of actors and items from map properties (a light RPG system for level-up access to new cosmetics etc. would be a lot of fun)
>   - Mission and reward system

For starters I’m most interested in easy game modification. We’re touching on that in #116, and @64kramsystem also made the point a long time ago in chat:

> is it worth making the weapons tweakable by non-technical users (I don't know if you're familiar with Rust). for example, if the parameters were in a text file, playtesters could trivially edit the file and see which parameters are the most fun. This is absolutely trivial to implement (on a per-weapon basis).

**Comment by olefasting** [comment]
I have been discussing this with Erlend today and I am currently working on separating out the map portion of my toolkit for a proposed integration with FF. I also have a lot of helpers and utility methods related to UI, like builders for various widgets, menus and theming that I will try to adapt. My approach has been to utilize tiled props to drive most of the scene construction and spawning, as well as automate collision detection setup etc. It is also easier to work with my format, imo, as it uses HashMaps for most things, internally, so that it is easier to access elements. Properties are also handled better and I have implemented props on most things that have props in the Tiled spec (MQ's tiled only allow props for layers, if I recall correctly).

This should all ease the process of making a level editor...

**Comment by erlend-sh** [comment]
With our v0.3 release we’ve acquired all the essential toolkit features available to us 🥰 🚀
