### ISSUE TITLE
Can't Build SDL2 on Wayland

### ISSUE THREAD

**Issue by billyb2** [fishfight/FishFight#309]
When I try to run `cargo run`, once it reaches the sdl2-sys dependency I get this compile time error:

```
  running: "cmake" "--build" "." "--target" "install" "--config" "release" "--parallel" "2"
  Consolidate compiler generated dependencies of target SDL2main
  [  1%] Built target SDL2main
  Consolidate compiler generated dependencies of target SDL2
  [  2%] Linking C shared library libSDL2-2.0.so

  --- stderr
  make: warning: -j2 forced in submake: resetting jobserver mode.
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_source_destroy':
  SDL_waylanddatamanager.c:(.text.Wayland_data_source_destroy+0x3f): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_offer_receive':
  SDL_waylanddatamanager.c:(.text.Wayland_data_offer_receive+0x97): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_offer_destroy':
  SDL_waylanddatamanager.c:(.text.Wayland_data_offer_destroy+0x3f): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_device_clear_selection':
  SDL_waylanddatamanager.c:(.text.Wayland_data_device_clear_selection+0x44): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_device_set_selection':
  SDL_waylanddatamanager.c:(.text.Wayland_data_device_set_selection+0x85): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o:SDL_waylanddatamanager.c:(.text.Wayland_data_device_set_selection+0x115): more undefined references to `wl_proxy_marshal_flags' follow
  collect2: error: ld returned 1 exit status
  make[2]: *** [CMakeFiles/SDL2.dir/build.make:3209: libSDL2-2.0.so.0.16.0] Error 1
  make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/SDL2.dir/all] Error 2
```

**Comment by orhun** [comment]
Hello, thanks for reporting this!

This seems like a problem about [fishsticks](https://github.com/PotatoTech/fishsticks) dependency since it uses bundled [sdl2](https://github.com/Rust-SDL2/rust-sdl2). (So maybe @PotatoTech can say something about this.) Also, I recommend reporting this to [rust-sdl2](https://github.com/Rust-SDL2/rust-sdl2) since they had similar issues in the past. ([#1169](https://github.com/Rust-SDL2/rust-sdl2/issues/1169), [#1011](https://github.com/Rust-SDL2/rust-sdl2/issues/1011)) Other than that, I don't think there's much we can do here.

**Comment by erlend-sh** [comment]
fishsticks also supports gilrs as a backend. Could anyone running into this switch to that instead?

**Comment by billyb2** [comment]
To switch to girls. Would I just set the feature flag in fishsticks?

**Comment by billyb2** [comment]
Just submitted an issue

**Comment by erlend-sh** [comment]
> To switch to gilrs, would I just set the feature flag in fishsticks?

That’s what I’m hoping might be possible, but it’s probably not that simple.

As a temporary workaround, you could try run a forked version using our old gamepad setup:

https://github.com/fishfight/FishFight/pull/177

**Comment by billyb2** [comment]
Disabling the bundled-sdl2 feature flag fixes compilation

**Comment by PotatoTech** [comment]
This issue was fixed in upstream SDL2 here: https://github.com/libsdl-org/SDL/pull/5092.
rust-sdl2 updated to the fixed version here: https://github.com/Rust-SDL2/rust-sdl2/pull/1186.

I will make a new release when rust-sdl2 publishes a release with this fix. If we do not want to wait for rust-sdl2 to release a new version, I can change fishsticks to use the git version. Fish Fight would also have to switch to using the git version of fishsticks.

**Comment by erlend-sh** [comment]
Great! Since Billy has found a workaround on his end for now, we’re fine to wait until there’s an upstream release 👍

**Comment by billyb2** [comment]
I can confirm that patching in the latest git version of sdl2 fixes the issue. Removing the bundled-sdl2 flag also does the trick

**Comment by orhun** [comment]
I'm also getting a similar build error on X11:

```
  --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  make: warning: -j4 forced in submake: resetting jobserver mode.
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_source_destroy':
  SDL_waylanddatamanager.c:(.text.Wayland_data_source_destroy+0x3f): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_offer_receive':
  SDL_waylanddatamanager.c:(.text.Wayland_data_offer_receive+0x97): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_offer_destroy':
  SDL_waylanddatamanager.c:(.text.Wayland_data_offer_destroy+0x3f): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_device_clear_selection':
  SDL_waylanddatamanager.c:(.text.Wayland_data_device_clear_selection+0x44): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o: in function `Wayland_data_device_set_selection':
  SDL_waylanddatamanager.c:(.text.Wayland_data_device_set_selection+0x85): undefined reference to `wl_proxy_marshal_flags'
  /usr/bin/ld: CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylanddatamanager.c.o:SDL_waylanddatamanager.c:(.text.Wayland_data_device_set_selection+0x115): more undefined references to `wl_proxy_marshal_flags' follow
  collect2: error: ld returned 1 exit status
  make[2]: *** [CMakeFiles/SDL2.dir/build.make:3193: libSDL2-2.0.so.0.16.0] Error 1
  make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/SDL2.dir/all] Error 2
  make: *** [Makefile:136: all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2
```

As mentioned, disabling `bundled-sdl2` solves this issue. Of course, we can do that and it would help in case the new release of SDL2 takes longer than we expected so that we won't hit this error again. However, we will no longer depend on `cmake` for building thus `sdl2` library should be provided by the system (e.g. [sdl2](https://archlinux.org/packages/extra/x86_64/sdl2/) should be installed on Arch Linux)

It seems to me that removing this feature is not really a disadvantage or advantage. As @erlend-sh said, we can wait a bit longer for the upstream but I wanted to point out this option as well. Thoughts?

**Comment by olefasting** [comment]
> It seems to me that removing this feature is not really a disadvantage or advantage. As @erlend-sh said, we can wait a bit longer for the upstream but I wanted to point out this option as well. Thoughts?

I think we should just disable this. The reason it is enabled is because we had some issues with mappings varying across input devices but I think that is a lot less problematic than such a prevalent build error.
For 1.0 release, we can enable it again when we make releases, if necessary, as well as have input mapping ready, so that users can manually correct erroneous mappings

**Comment by erlend-sh** [comment]
Yes exactly, better have it the other way around: put in a notice for the edge case users to enable if needed.

**Comment by olefasting** [comment]
We should probably put input mappings up on the priority list, then. I have made input a bit different now; separating control and input, much like is done in UE, for example. This is so that controller can be generalized for local input, network and AI, with local input just being one of many methods to drive the player controller. I can also just quickly make it so that mappings for local input is pulled from the config struct, thus implementing input mappings via config file, until we have proper UI for this...

**Comment by orhun** [comment]
It looks like we might want to re-enable the `bundled-sdl2` feature as we come closer to release the new version. I've been experimenting with building FF for different targets and SDL2 dependency creates an overhead while building via GitHub actions.

**Comment by olefasting** [comment]
Yeah, personally, I would prefer bundled as it gives us version control

**Comment by orhun** [comment]
SDL2 is no longer a dependency.
