### ISSUE TITLE
Critters

### ISSUE THREAD

**Issue by SirGiraffey** [fishfight/FishFight#337]
Critters would be small entities with relatively simple AI and animations. They wouldn't affect the gameplay in any meaningful way, but  they would make the game feel much more organic.

Small Fish: They would float around the level randomly, maybe form clumps and wouldn't drift too far from each other. When a player gets too close they get scared and swim away. When a bullet passes closely, they could panic and swim away quickly, completely disorganizing the "group". If hit by a laser or a bullet, they could turn into a tiny skeleton (or sushi for family-friendliness) that drops to the ground.

Crabs: They would walk left-right randomly and stop for a few moments, but they wouldn't walk off ledges on their own. If a player gets too close they would walk away, and drop from platforms if there is no wall to stop them from doing so.

![obraz](https://user-images.githubusercontent.com/57463655/150713079-dda5dfdb-d1bc-4094-84d8-744cd537859c.png)
![obraz](https://user-images.githubusercontent.com/57463655/150713084-1f2446cc-1037-4586-a290-7b4b86434987.png)

**Comment by erlend-sh** [comment]
This is for sure happening 👍 Might also be related to #43 

And I would welcome more impactful gameplay affectations as well. These sorts of incremental embellishments are how we add unique character to our game and ensure that although it’s a spiritual successor, it has its own soul 💫

**Comment by SirGiraffey** [comment]
Just made a mock-up of another critter which could serve some gameplay purpose, but mainly be a great ambient feature, the angler fish. It glows in the dark!
![Critters 3](https://user-images.githubusercontent.com/57463655/156923979-c915e4ca-bcb9-4576-8b88-cef242ae6a1d.png)

**Comment by erlend-sh** [comment]
Update from @zTecna:

![819CFD6A-249A-4FB7-8CE0-0F07A7466A61](https://user-images.githubusercontent.com/583842/161223438-01b7d3c2-85e7-496a-a500-fac0e26611de.jpeg)

**Comment by zicklag** [comment]
I'm going to be working on this. If anybody could upload some of the raw sprites for the crabs and little fish that would help, but nothing's stopping me from just using some placeholder sprites, so it's not a big deal.

Also @erlend-sh I wanted double-check on the scope of the MVP. I'm thinking:

- We have crabs:
  - that can be placed on the map to define their spawn point
  - that can walk left and right randomly within a small distance
  - that will try to stay a minimum distance away from players by walking away from them
  - that, for the sake of scope for now, won't have any logic to avoid ledges
- We have fish:
  - that are placed on the map to define the spawn point of the "school"
  - that will wander around, but stay within a certain distance of the center of the school
  - that will scatter when a fish runs through the center of the school
  - that will re-form as a group after getting scattered
- Fish and crabs will be 100% aesthetic and in the background for now.

**Comment by zicklag** [comment]
@olefasting Do you think critters would be fancy decorations, or a new `MapItemKind::Critter`?

It seems like maybe they should be their own map item kind because in the future certain ones could effect the player, and a decoration should probably never do that.

**Comment by zicklag** [comment]
I got crabs working!

I think the simple AI for them turned out pretty nice looking. They like to hang out where they've spawned, and if they get scared away, the'll eventually end up back in the vicinity of their "happy place", assuming they haven't fallen off a platform! In that case they'll just try to get in roughly the same horizontal position of their happy place.

They don't like big scary fishes ( the players ) and they'll run away from them. They apparently even bounce on sproingers with no extra effort on my part, which is hilarious.

I made a rough copy of the sprite above to use for them, but the shading isn't as nice so we can update the sprite later.

https://user-images.githubusercontent.com/25393315/162595716-d0645cb5-d411-4b70-9584-99c57f29af31.mp4

It's a little hard to tell with the low frame rate, but it's pretty fun how they panic if you kind of trap them between two fish. :smile: 

https://user-images.githubusercontent.com/25393315/162595729-5bb430ab-cb38-4a4f-92b7-b4980aa9ef5f.mp4

Here's the PR: https://github.com/fishfight/FishFight/pull/417.

**Comment by zicklag** [comment]
Sure thing! I'm not sure how you guys usually add the artwork. Do you usually push a commit with the artwork so that you get attribution in the git history?

However you do it, if you want to, you could upload the animation or push a commit to a fork with the crab sprite in it, and I can integrate it into the pull request. Animating him would be very easy.

In the future me and my brother were even thinking the crabs might be able to dig into the floor to despawn and then dig back out in their spawn point if they got "lost".

**Comment by erlend-sh** [comment]
#417 is merged! 🤗 

@zicklag could you make a final demonstration video of this for sharing on Twitter? The more square-shaped and close-up the better, preferably without the hats & shell, as we haven’t yet fine-tuned those attachments to look really good in-game.

**Comment by zicklag** [comment]
Sure I'll try to get a decent video made, hopefully tomorrow.

**Comment by zTecna** [comment]
> > I usually send a compressed file of the sprites by discord because I don't know how exactly the programmer will use and organize them. but i think i learned how to do the pull request i'm not so sure
> 
> If the file has metadata that says you are the author, then it should be fine for you to upload the zip to GitHub and I could submit a PR for it. Or you could send it to another developer who's on Discord ( 'cause I'm not on Discord ).
> 
> Whatever you want to do. 🙂

I have a drive where I will publish future and current sprites, if you want I can upload them and put the link for you here

**Comment by zicklag** [comment]
I'll wait for another dev to do it, because I've got a weird network setup that will block a lot of sites and I probably won't be able to get to the drive.

**Comment by zTecna** [comment]
> I'll wait for another dev to do it, because I've got a weird network setup that will block a lot of sites and I probably won't be able to get to the drive.

even with google stuff? that's weird, but I'll see if I can make a pull request

**Comment by zicklag** [comment]
> even with google stuff?

Yeah, it's a unique scenario. :smile: 

---

Anyway, you should just be able to click and drag the file into a GitHub comment for any PNG or zip files, I think if you don't want to do a PR.

**Comment by zTecna** [comment]
![critters](https://user-images.githubusercontent.com/98235607/163263015-786844f2-1bc4-41fe-989b-4688b4759dbc.png)
I left all the animations this way because I don't know how you're going to fit them. if you need me to make it easier, just tell me how and I'm going to do it!

**Comment by zicklag** [comment]
That will be fine, thanks!

**Comment by zicklag** [comment]
I got fishes working!

https://user-images.githubusercontent.com/25393315/163492607-8bdfa3bc-2e6e-41db-ab53-81b8a05d36d3.mp4

I used @zTecna's sprites for this demo, and updated the crabs, too. I had also tried some smaller fish with more fish in each school and that looked rather nice, too.

It seems like we could have these bigger fish and smaller fish like in the picture in the original post as separate kinds of schools, but for now we've just got this one kind, and we'll eventually want to add fish schools as a kind of item that could be added through JSON so that users can create their own school types, probably.

I'll try to get a more proper video and pull requests for fish out as soon as I can.

**Comment by zicklag** [comment]
@erlend-sh Here's a better video you could use for any progress sharing:

https://user-images.githubusercontent.com/25393315/163692406-f4c7e872-5aeb-4f29-973d-cc0b50ed071c.mp4

**Comment by zicklag** [comment]
@SirGiraffey ( or anybody else who has the sprites ) could you upload the tiny fish sprites to GitHub here.

Unless we have other plans, I wanted to add the smaller fish school as a different style school, with the same logic, but different sprites and maybe a higher average fish per school count.

Also, do we want to have the different style crabs, too?

**Comment by SirGiraffey** [comment]
I can send the tiny sprites I made as sketches to show my idea, but I think they should be revised by the artists at some poin
![Critters Small Sprites](https://user-images.githubusercontent.com/57463655/169873749-0b604733-085d-4d57-a06f-31fd7ab8d2b7.png)
t
